# coding: utf-8

"""
    Traffic Generator Service

    Traffic generator service for the NI project.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import trafgen_module_client
from trafgen_module_client.models.sfcr import SFCR  # noqa: E501
from trafgen_module_client.rest import ApiException


class TestSFCR(unittest.TestCase):
    """SFCR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSFCR(self):
        """Test SFCR"""
        # FIXME: construct object with mandatory attributes with example values
        # model = trafgen_module_client.models.sfcr.SFCR()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
